title: Laura Risley
url: "https://laurarisley.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Research"
   link: "research"
 - name: "Academic Experience"
   link: "academic"
 - name: "Blog"
   link: "blog"
 - name: "DARC"
   link: "darc"
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-dinky
